web:
  build: .
  command: php -S 0.0.0.0:8000 -t /code/SuiteCRM
  ports:
    - "8000:8000"
  links:
    - db
  volumes:
    - .:/code
db:
  image: orchardup/mysql
  environment:
    MYSQL_DATABASE: suitecrm
